/**
 * wrapper.js — Max-side glue (NOT the React app).
 *
 * Runs in Max's [js] object. Uses LiveAPI to observe whether THIS track is
 * actively recording, and forwards a single "record 1" / "record 0" message
 * to the [jweb] object, which the React app picks up via max.bindInlet("record").
 *
 * Diagnostics use post() so they appear in the Max Console (Window → Max Console)
 * with no wiring required.
 *
 * Outlets:
 *   0 — to jweb   ("url <file://…>" on load, then "record 1" / "record 0")
 *   1 — to print  (optional)
 */

autowatch = 1;
inlets = 1;
outlets = 2;

// Liveness banner — prints the moment the script (re)loads. If you don't see
// this in the Max Console, the [js wrapper.js] object isn't in the device.
post("wrapper.js loaded\n");

var isArmed = 0;
var isPlaying = 0;
var isRecordMode = 0;
var recording = -1; // force first emit

var armObs = null;
var playObs = null;
var recObs = null;

// live.thisdevice bang lands here once the device is fully initialized.
function bang() {
	post("livecam: thisdevice bang\n");
	setup();
}

function loadbang() {
	post("livecam: loadbang\n");
	setup();
}

// A plain message you can send from a [message] box to re-run setup on demand.
function reload() {
	post("livecam: manual reload\n");
	setup();
}

function setup() {
	teardown();
	loadWebview();
	try {
		armObs = new LiveAPI(onArm, "this_device canonical_parent");
		armObs.property = "arm";

		playObs = new LiveAPI(onPlay, "live_set");
		playObs.property = "is_playing";

		recObs = new LiveAPI(onRec, "live_set");
		recObs.property = "record_mode";

		post("livecam: observers ready\n");
	} catch (e) {
		post("livecam: setup error " + e.message + "\n");
	}
}

function teardown() {
	armObs = null;
	playObs = null;
	recObs = null;
}

function loadWebview() {
	try {
		var url = resolveUiUrl();
		if (!url) return;
		outlet(0, "url", url);
		post("livecam: sent url " + url + "\n");
	} catch (e) {
		post("livecam: loadWebview error " + e.message + "\n");
	}
}

/**
 * Locate the UI html and return a file:// URL that Chromium (jweb) can read.
 *
 * The build appends the UI to this very script as a base64 payload
 * (UI_PAYLOAD_B64 / UI_PAYLOAD_BYTES, generated by build-amxd.mjs). Frozen
 * dependencies only exist in Max's virtual filesystem, which Chromium can't
 * read - but this script provably runs, so it extracts the payload to a real
 * file next to the .amxd and points jweb at that. Without a payload (repo /
 * dev layout) it falls back to the loose copy next to the patcher.
 */
var UI_NAME = "livecam-ui.html";

function resolveUiUrl() {
	var fp = this.patcher.filepath;
	var devFolder = fp && fp.length ? fp.replace(/\/[^\/]*$/, "") : null;
	if (!devFolder) {
		post("livecam: patcher not saved yet - UI path unknown\n");
		return null;
	}
	var target = devFolder + "/" + UI_NAME;
	if (typeof UI_PAYLOAD_B64 !== "undefined") {
		extractPayloadIfNeeded(target);
	} else {
		post("livecam: no embedded payload (dev build) - using " + target + "\n");
	}
	return encodeURI("file:///" + target);
}

/** Write the embedded payload to targetPath unless an identical-size copy exists. */
function extractPayloadIfNeeded(targetPath) {
	try {
		var existing = new File(targetPath);
		if (existing.isopen) {
			var sameSize = existing.eof === UI_PAYLOAD_BYTES;
			existing.close();
			if (sameSize) return; // already extracted, same build
		}
	} catch (e) {
		/* fall through to (re)write */
	}
	try {
		var out = new File(targetPath, "write");
		if (!out.isopen) out.open();
		if (!out.isopen) {
			post("livecam: cannot write " + targetPath + "\n");
			return;
		}
		out.eof = 0;
		var bytes = [];
		for (var i = 0; i < UI_PAYLOAD_B64.length; i++) {
			var part = b64decode(UI_PAYLOAD_B64[i]);
			for (var p = 0; p < part.length; p++) bytes.push(part[p]);
		}
		if (typeof UI_PAYLOAD_DEFLATE !== "undefined" && UI_PAYLOAD_DEFLATE) {
			bytes = inflateRaw(bytes);
		}
		// File.writebytes silently truncates large calls (observed 16384-byte
		// cap), so write in small slices.
		var SLICE = 4096;
		for (var off = 0; off < bytes.length; off += SLICE) {
			out.writebytes(bytes.slice(off, off + SLICE));
		}
		out.close();
		var check = new File(targetPath);
		var written = check.isopen ? check.eof : -1;
		if (check.isopen) check.close();
		if (written === UI_PAYLOAD_BYTES) {
			post("livecam: extracted UI (" + written + " bytes) to " + targetPath + "\n");
		} else {
			post("livecam: extract SIZE MISMATCH - wrote " + written + ", expected " + UI_PAYLOAD_BYTES + "\n");
		}
	} catch (e2) {
		post("livecam: extract failed - " + e2.message + "\n");
	}
}

/**
 * Minimal raw-DEFLATE (RFC 1951) decoder, "puff"-style. The build compresses
 * the UI payload with zlib deflateRaw; this inflates it back to exact bytes.
 * ES5 only - Max's js object has no zlib/atob.
 */
function inflateRaw(src) {
	var pos = 0;
	var bitbuf = 0;
	var bitcnt = 0;
	var out = [];

	function bits(need) {
		while (bitcnt < need) {
			if (pos >= src.length) throw new Error("inflate: out of input");
			bitbuf |= src[pos++] << bitcnt;
			bitcnt += 8;
		}
		var val = bitbuf & ((1 << need) - 1);
		bitbuf >>>= need;
		bitcnt -= need;
		return val;
	}

	function construct(lengths, n) {
		var h = { count: [], symbol: [] };
		var len, i;
		for (len = 0; len <= 15; len++) h.count[len] = 0;
		for (i = 0; i < n; i++) h.count[lengths[i]]++;
		h.count[0] = 0;
		var offs = [0, 0];
		for (len = 1; len <= 15; len++) offs[len + 1] = offs[len] + h.count[len];
		for (i = 0; i < n; i++) if (lengths[i]) h.symbol[offs[lengths[i]]++] = i;
		return h;
	}

	function decode(h) {
		var code = 0;
		var first = 0;
		var index = 0;
		for (var len = 1; len <= 15; len++) {
			code |= bits(1);
			var count = h.count[len];
			if (code - first < count) return h.symbol[index + (code - first)];
			index += count;
			first = (first + count) << 1;
			code <<= 1;
		}
		throw new Error("inflate: bad code");
	}

	var LENS = [3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258];
	var LEXT = [0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0];
	var DISTS = [1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,1537,2049,3073,4097,6145,8193,12289,16385,24577];
	var DEXT = [0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13];

	function codes(lencode, distcode) {
		while (true) {
			var sym = decode(lencode);
			if (sym < 256) {
				out.push(sym);
			} else if (sym === 256) {
				return;
			} else {
				sym -= 257;
				var len = LENS[sym] + bits(LEXT[sym]);
				var dsym = decode(distcode);
				var dist = DISTS[dsym] + bits(DEXT[dsym]);
				var from = out.length - dist;
				if (from < 0) throw new Error("inflate: bad distance");
				for (var k = 0; k < len; k++) out.push(out[from + k]);
			}
		}
	}

	var fixedLen = null;
	var fixedDist = null;

	function fixed() {
		if (!fixedLen) {
			var lengths = [];
			var i;
			for (i = 0; i < 144; i++) lengths[i] = 8;
			for (; i < 256; i++) lengths[i] = 9;
			for (; i < 280; i++) lengths[i] = 7;
			for (; i < 288; i++) lengths[i] = 8;
			fixedLen = construct(lengths, 288);
			var dl = [];
			for (i = 0; i < 30; i++) dl[i] = 5;
			fixedDist = construct(dl, 30);
		}
		codes(fixedLen, fixedDist);
	}

	var ORDER = [16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15];

	function dynamic() {
		var nlen = bits(5) + 257;
		var ndist = bits(5) + 1;
		var ncode = bits(4) + 4;
		var lengths = [];
		var i;
		for (i = 0; i < 19; i++) lengths[ORDER[i]] = 0;
		for (i = 0; i < ncode; i++) lengths[ORDER[i]] = bits(3);
		var lencode = construct(lengths, 19);
		lengths = [];
		i = 0;
		while (i < nlen + ndist) {
			var sym = decode(lencode);
			if (sym < 16) {
				lengths[i++] = sym;
			} else if (sym === 16) {
				var prev = lengths[i - 1];
				var rep = 3 + bits(2);
				while (rep--) lengths[i++] = prev;
			} else if (sym === 17) {
				var rep2 = 3 + bits(3);
				while (rep2--) lengths[i++] = 0;
			} else {
				var rep3 = 11 + bits(7);
				while (rep3--) lengths[i++] = 0;
			}
		}
		codes(construct(lengths, nlen), construct(lengths.slice(nlen), ndist));
	}

	function stored() {
		bitbuf = 0;
		bitcnt = 0;
		var len = src[pos] | (src[pos + 1] << 8);
		pos += 4; // skip LEN + NLEN
		for (var i = 0; i < len; i++) out.push(src[pos++]);
	}

	var last;
	do {
		last = bits(1);
		var type = bits(2);
		if (type === 0) stored();
		else if (type === 1) fixed();
		else if (type === 2) dynamic();
		else throw new Error("inflate: bad block type");
	} while (!last);
	return out;
}

var B64CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
var b64lookup = null;

/** Base64 → array of byte values (Max js has no atob). */
function b64decode(s) {
	if (!b64lookup) {
		b64lookup = {};
		for (var i = 0; i < B64CHARS.length; i++) b64lookup[B64CHARS.charAt(i)] = i;
	}
	var out = [];
	var buffer = 0;
	var bits = 0;
	for (var j = 0; j < s.length; j++) {
		var c = s.charAt(j);
		if (c === "=") break;
		buffer = (buffer << 6) | b64lookup[c];
		bits += 6;
		if (bits >= 8) {
			bits -= 8;
			out.push((buffer >> bits) & 0xff);
		}
	}
	return out;
}

function onArm(a) {
	if (a && a.length >= 2 && a[0] == "arm") {
		isArmed = a[1];
		evaluate();
	}
}

function onPlay(a) {
	if (a && a.length >= 2 && a[0] == "is_playing") {
		isPlaying = a[1];
		evaluate();
	}
}

function onRec(a) {
	if (a && a.length >= 2 && a[0] == "record_mode") {
		isRecordMode = a[1];
		evaluate();
	}
}

// The three observers (arm / is_playing / record_mode) fire as separate,
// non-atomic callbacks when the transport starts, so the combined condition can
// briefly flap true→false→true. Debounce with a 150 ms settle so only the final
// state is emitted — otherwise a transient "record 1" then "record 0" makes the
// UI start and immediately stop, writing an empty clip.
var settleTask = null;
var pendingRecord = -1;

function evaluate() {
	var shouldRecord = isArmed && isPlaying && isRecordMode ? 1 : 0;
	if (shouldRecord === recording) {
		// Settled back to what we already emitted — cancel any pending flip.
		if (settleTask) {
			settleTask.cancel();
			settleTask = null;
		}
		return;
	}
	pendingRecord = shouldRecord;
	if (settleTask) settleTask.cancel();
	settleTask = new Task(emitRecord, this);
	settleTask.schedule(150);
}

function emitRecord() {
	settleTask = null;
	if (pendingRecord === recording) return;
	recording = pendingRecord;
	outlet(0, "record", recording);
	post("livecam: record " + recording + "\n");
}
