/**
 * wrapper.js — Max-side glue (NOT the React app).
 *
 * Runs in Max's [js] object. Uses LiveAPI to observe whether THIS track is
 * actively recording, and forwards a single "record 1" / "record 0" message
 * to the [jweb] object, which the React app picks up via max.bindInlet("record").
 *
 * Diagnostics use post() so they appear in the Max Console (Window → Max Console)
 * with no wiring required.
 *
 * Outlets:
 *   0 — to jweb   ("url <file://…>" on load, then "record 1" / "record 0")
 *   1 — to print  (optional)
 */

autowatch = 1;
inlets = 1;
outlets = 2;

// Liveness banner — prints the moment the script (re)loads. If you don't see
// this in the Max Console, the [js wrapper.js] object isn't in the device.
post("wrapper.js loaded\n");

var isArmed = 0;
var isPlaying = 0;
var isRecordMode = 0;
var recording = -1; // force first emit

var armObs = null;
var playObs = null;
var recObs = null;

// live.thisdevice bang lands here once the device is fully initialized.
function bang() {
	post("livecam: thisdevice bang\n");
	setup();
}

function loadbang() {
	post("livecam: loadbang\n");
	setup();
}

// A plain message you can send from a [message] box to re-run setup on demand.
function reload() {
	post("livecam: manual reload\n");
	setup();
}

function setup() {
	teardown();
	loadWebview();
	try {
		armObs = new LiveAPI(onArm, "this_device canonical_parent");
		armObs.property = "arm";

		playObs = new LiveAPI(onPlay, "live_set");
		playObs.property = "is_playing";

		recObs = new LiveAPI(onRec, "live_set");
		recObs.property = "record_mode";

		post("livecam: observers ready\n");
	} catch (e) {
		post("livecam: setup error " + e.message + "\n");
	}
}

function teardown() {
	armObs = null;
	playObs = null;
	recObs = null;
}

function loadWebview() {
	try {
		var url = resolveUiUrl();
		if (!url) return;
		outlet(0, "url", url);
		post("livecam: sent url " + url + "\n");
	} catch (e) {
		post("livecam: loadWebview error " + e.message + "\n");
	}
}

/**
 * Locate the UI html and return a file:// URL that Chromium (jweb) can read.
 *
 * The build appends the UI to this very script as a base64 payload
 * (UI_PAYLOAD_B64 / UI_PAYLOAD_BYTES, generated by build-amxd.mjs). Frozen
 * dependencies only exist in Max's virtual filesystem, which Chromium can't
 * read - but this script provably runs, so it extracts the payload to a real
 * file next to the .amxd and points jweb at that. Without a payload (repo /
 * dev layout) it falls back to the loose copy next to the patcher.
 */
var UI_NAME = "livecam-ui.html";

function resolveUiUrl() {
	var fp = this.patcher.filepath;
	var devFolder = fp && fp.length ? fp.replace(/\/[^\/]*$/, "") : null;
	if (!devFolder) {
		post("livecam: patcher not saved yet - UI path unknown\n");
		return null;
	}
	var target = devFolder + "/" + UI_NAME;
	if (typeof UI_PAYLOAD_B64 !== "undefined") {
		extractPayloadIfNeeded(target);
	} else {
		post("livecam: no embedded payload (dev build) - using " + target + "\n");
	}
	return encodeURI("file:///" + target);
}

/** Write the embedded payload to targetPath unless an identical-size copy exists. */
function extractPayloadIfNeeded(targetPath) {
	try {
		var existing = new File(targetPath);
		if (existing.isopen) {
			var sameSize = existing.eof === UI_PAYLOAD_BYTES;
			existing.close();
			if (sameSize) return; // already extracted, same build
		}
	} catch (e) {
		/* fall through to (re)write */
	}
	try {
		var out = new File(targetPath, "write");
		if (!out.isopen) out.open();
		if (!out.isopen) {
			post("livecam: cannot write " + targetPath + "\n");
			return;
		}
		out.eof = 0;
		// File.writebytes silently truncates large calls (observed 16384-byte
		// cap), so write in small slices.
		var SLICE = 4096;
		for (var i = 0; i < UI_PAYLOAD_B64.length; i++) {
			var bytes = b64decode(UI_PAYLOAD_B64[i]);
			for (var off = 0; off < bytes.length; off += SLICE) {
				out.writebytes(bytes.slice(off, off + SLICE));
			}
		}
		out.close();
		var check = new File(targetPath);
		var written = check.isopen ? check.eof : -1;
		if (check.isopen) check.close();
		if (written === UI_PAYLOAD_BYTES) {
			post("livecam: extracted UI (" + written + " bytes) to " + targetPath + "\n");
		} else {
			post("livecam: extract SIZE MISMATCH - wrote " + written + ", expected " + UI_PAYLOAD_BYTES + "\n");
		}
	} catch (e2) {
		post("livecam: extract failed - " + e2.message + "\n");
	}
}

var B64CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
var b64lookup = null;

/** Base64 → array of byte values (Max js has no atob). */
function b64decode(s) {
	if (!b64lookup) {
		b64lookup = {};
		for (var i = 0; i < B64CHARS.length; i++) b64lookup[B64CHARS.charAt(i)] = i;
	}
	var out = [];
	var buffer = 0;
	var bits = 0;
	for (var j = 0; j < s.length; j++) {
		var c = s.charAt(j);
		if (c === "=") break;
		buffer = (buffer << 6) | b64lookup[c];
		bits += 6;
		if (bits >= 8) {
			bits -= 8;
			out.push((buffer >> bits) & 0xff);
		}
	}
	return out;
}

function onArm(a) {
	if (a && a.length >= 2 && a[0] == "arm") {
		isArmed = a[1];
		evaluate();
	}
}

function onPlay(a) {
	if (a && a.length >= 2 && a[0] == "is_playing") {
		isPlaying = a[1];
		evaluate();
	}
}

function onRec(a) {
	if (a && a.length >= 2 && a[0] == "record_mode") {
		isRecordMode = a[1];
		evaluate();
	}
}

// The three observers (arm / is_playing / record_mode) fire as separate,
// non-atomic callbacks when the transport starts, so the combined condition can
// briefly flap true→false→true. Debounce with a 150 ms settle so only the final
// state is emitted — otherwise a transient "record 1" then "record 0" makes the
// UI start and immediately stop, writing an empty clip.
var settleTask = null;
var pendingRecord = -1;

function evaluate() {
	var shouldRecord = isArmed && isPlaying && isRecordMode ? 1 : 0;
	if (shouldRecord === recording) {
		// Settled back to what we already emitted — cancel any pending flip.
		if (settleTask) {
			settleTask.cancel();
			settleTask = null;
		}
		return;
	}
	pendingRecord = shouldRecord;
	if (settleTask) settleTask.cancel();
	settleTask = new Task(emitRecord, this);
	settleTask.schedule(150);
}

function emitRecord() {
	settleTask = null;
	if (pendingRecord === recording) return;
	recording = pendingRecord;
	outlet(0, "record", recording);
	post("livecam: record " + recording + "\n");
}
